# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import speech_to_text_pb2 as speech__to__text__pb2


class SpeechToTextStub(object):
  """Speech To Text service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Recognition = channel.unary_unary(
        '/speech_to_text.SpeechToText/Recognition',
        request_serializer=speech__to__text__pb2.Request.SerializeToString,
        response_deserializer=speech__to__text__pb2.Response.FromString,
        )


class SpeechToTextServicer(object):
  """Speech To Text service definition.
  """

  def Recognition(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SpeechToTextServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Recognition': grpc.unary_unary_rpc_method_handler(
          servicer.Recognition,
          request_deserializer=speech__to__text__pb2.Request.FromString,
          response_serializer=speech__to__text__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'speech_to_text.SpeechToText', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
