# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: new_demo_portal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='new_demo_portal.proto',
  package='new_demo_portal',
  syntax='proto3',
  serialized_pb=_b('\n\x15new_demo_portal.proto\x12\x0fnew_demo_portal\"\x1b\n\x07Request\x12\x10\n\x08sentence\x18\x01 \x01(\t\"\x1d\n\x08Response\x12\x11\n\texec_time\x18\x01 \x01(\x02\x32Q\n\rNewDemoPortal\x12@\n\x07\x41nalyze\x12\x18.new_demo_portal.Request\x1a\x19.new_demo_portal.Response\"\x00\x62\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='new_demo_portal.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='new_demo_portal.Request.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=69,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='new_demo_portal.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exec_time', full_name='new_demo_portal.Response.exec_time', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'new_demo_portal_pb2'
  # @@protoc_insertion_point(class_scope:new_demo_portal.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'new_demo_portal_pb2'
  # @@protoc_insertion_point(class_scope:new_demo_portal.Response)
  ))
_sym_db.RegisterMessage(Response)



_NEWDEMOPORTAL = _descriptor.ServiceDescriptor(
  name='NewDemoPortal',
  full_name='new_demo_portal.NewDemoPortal',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=102,
  serialized_end=183,
  methods=[
  _descriptor.MethodDescriptor(
    name='Analyze',
    full_name='new_demo_portal.NewDemoPortal.Analyze',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NEWDEMOPORTAL)

DESCRIPTOR.services_by_name['NewDemoPortal'] = _NEWDEMOPORTAL

# @@protoc_insertion_point(module_scope)
