# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import new_demo_portal_pb2 as new__demo__portal__pb2


class NewDemoPortalStub(object):
  """Prime factors service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Analyze = channel.stream_stream(
        '/new_demo_portal.NewDemoPortal/Analyze',
        request_serializer=new__demo__portal__pb2.Request.SerializeToString,
        response_deserializer=new__demo__portal__pb2.Response.FromString,
        )


class NewDemoPortalServicer(object):
  """Prime factors service definition.
  """

  def Analyze(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NewDemoPortalServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Analyze': grpc.stream_stream_rpc_method_handler(
          servicer.Analyze,
          request_deserializer=new__demo__portal__pb2.Request.FromString,
          response_serializer=new__demo__portal__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'new_demo_portal.NewDemoPortal', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
