# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: new_demo_portal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import speaker_emotion_pb2 as speaker__emotion__pb2
import speech_to_text_pb2 as speech__to__text__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='new_demo_portal.proto',
  package='new_demo_portal',
  syntax='proto3',
  serialized_pb=_b('\n\x15new_demo_portal.proto\x12\x0fnew_demo_portal\x1a\x15speaker_emotion.proto\x1a\x14speech_to_text.proto\"2\n\x07Request\x12\x12\n\x06signal\x18\x01 \x03(\x02\x42\x02\x10\x01\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\"p\n\x08Response\x12&\n\x06speech\x18\x01 \x01(\x0b\x32\x16.speech_to_text.Speech\x12)\n\x07\x65motion\x18\x02 \x01(\x0b\x32\x18.speaker_emotion.Emotion\x12\x11\n\texec_time\x18\x03 \x01(\x02\x32U\n\rNewDemoPortal\x12\x44\n\x07\x41nalyze\x12\x18.new_demo_portal.Request\x1a\x19.new_demo_portal.Response\"\x00(\x01\x30\x01\x62\x06proto3')
  ,
  dependencies=[speaker__emotion__pb2.DESCRIPTOR,speech__to__text__pb2.DESCRIPTOR,])




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='new_demo_portal.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signal', full_name='new_demo_portal.Request.signal', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sample_rate', full_name='new_demo_portal.Request.sample_rate', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=137,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='new_demo_portal.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speech', full_name='new_demo_portal.Response.speech', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='emotion', full_name='new_demo_portal.Response.emotion', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exec_time', full_name='new_demo_portal.Response.exec_time', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=251,
)

_RESPONSE.fields_by_name['speech'].message_type = speech__to__text__pb2._SPEECH
_RESPONSE.fields_by_name['emotion'].message_type = speaker__emotion__pb2._EMOTION
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'new_demo_portal_pb2'
  # @@protoc_insertion_point(class_scope:new_demo_portal.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'new_demo_portal_pb2'
  # @@protoc_insertion_point(class_scope:new_demo_portal.Response)
  ))
_sym_db.RegisterMessage(Response)


_REQUEST.fields_by_name['signal'].has_options = True
_REQUEST.fields_by_name['signal']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))

_NEWDEMOPORTAL = _descriptor.ServiceDescriptor(
  name='NewDemoPortal',
  full_name='new_demo_portal.NewDemoPortal',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=253,
  serialized_end=338,
  methods=[
  _descriptor.MethodDescriptor(
    name='Analyze',
    full_name='new_demo_portal.NewDemoPortal.Analyze',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NEWDEMOPORTAL)

DESCRIPTOR.services_by_name['NewDemoPortal'] = _NEWDEMOPORTAL

# @@protoc_insertion_point(module_scope)
